import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/index.module.css';
import IndexPageFeed from '../components/feeds/bunch/IndexPageFeed';
import IndexPageHome from '../components/home/bunch/IndexPageHome';
import { useSession } from 'next-auth/react';
import { useState, useEffect, createContext } from 'react';
// import '../typings/user';
import { getUserByEmail } from '../lib/getUserByEmail';
import { API_Link } from '../config/config';
import { ThemeContext } from '../context/UserProvider';
import axios from 'axios';

interface UserContextType {
  users: User | [] | undefined;
  setUsers: (users: User) => void;
}

const UserContext = createContext<UserContextType>({
  users: [],
  setUsers: () => {},
});

const Home: NextPage = () => {
  const [users, setUsers] = useState<User | null>(null);
  const [dataa, setData] = useState<ResponseData | null>(null);

  const { data: session, status } = useSession();

  useEffect(() => {
    if (session && session.user) {
      const { name, email } = session.user;
      if (!name || !email) {
        return;
      } else {
        const handlePost = async () => {
          const data = {
            name: name,
            email: email,
          };
          if (dataa == null) {
            const response = await axios.post<ResponseData>(
              '/api/user/post',
              data
            );
            // console.log(response.data);
            setData(response.data);
            setUsers(response.data.data);
          }
        };
        handlePost();
      }
      // fetchUser(email);
    }
  }, [session, dataa, users]);

  // console.log(users);

  return (
    <div>
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeContext.Provider value={{ user: users }}>
        <div className={styles.index__container}>
          <div className={styles.index__content}>
            <IndexPageHome />
          </div>
          <div className={styles.index__feeds}>
            <IndexPageFeed />
          </div>
        </div>
      </ThemeContext.Provider>
    </div>
  );
};

export default Home;
export { UserContext };
