import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from "../styles/index.module.css"
import IndexPageFeed from '../components/feeds/bunch/IndexPageFeed'
import IndexPageHome from '../components/home/bunch/IndexPageHome'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.index__container}>
        <div className={styles.index__content}>
          <IndexPageHome/>
        </div>
        <div className={styles.index__feeds}>
          <IndexPageFeed />
        </div>
      </div>
    </div>
  );
}

export default Home
