import type { NextPage } from 'next';
import Head from 'next/head';
import IndexPageFeed from '../components/feeds/bunch/IndexPageFeed';
import IndexNotification from '../components/notification/bunch/IndexNotification';
import styles from "../styles/index.module.css";


const Notification:NextPage = () => {
  return (
    <div>
      <Head>
        <title>Notification</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.index__container}>
        <div className={styles.index__content}>
          <IndexNotification/>
        </div>
        <div className={styles.index__feeds}>
          <IndexPageFeed />
        </div>
      </div>
    </div>
  );
};

export default Notification;
