import type { NextPage } from 'next';
import Head from 'next/head';
import IndexPageFeed from '../components/feeds/bunch/IndexPageFeed';
import styles from '../styles/index.module.css';
import Profile from "../components/profile/bunch/ProfileIndex"

const profile = () => {
  return (
    <div>
      <Head>
        <title>Twitter 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.index__container}>
        <div className={styles.index__content}>
          <Profile/>
        </div>
        <div className={styles.index__feeds}>
          <IndexPageFeed />
        </div>
      </div>
    </div>
  );
};

export default profile;
